version: '3'
services:

  weba:
    hostname: webserver-a
    container_name: weba
    image: app
  webb:
    hostname: webserver-b
    container_name: webb
    image: app

  haproxy:
    hostname: haproxy
    container_name: haproxy
    image: haproxy
    links:
     - weba
     - webb
    ports:
     - "80:80"
     - "70:70"
    expose:
     - "80"
     - "70"
