---
- name: enable epel repo
  yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: install libvirt
  yum:
    name: libvirt
    state: present

- name: start and enable libvirt
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: add user to libvirt group
  user:
    name: "{{ user }}"
    groups: libvirt
    append: yes

- name: install vagrant on CentOS 7
  yum:
    name: https://releases.hashicorp.com/vagrant/2.2.1/vagrant_2.2.1_x86_64.rpm
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: install requirements for vagrant
  yum:
    name: libxslt-devel,libxml2-devel,libvirt-devel,libguestfs-tools-c,ruby-devel,gcc,rsync
    state: present

- name: install vagrant and vagrant-libvirt
  yum:
    name: vagrant,vagrant-libvirt
    state: present
  when: ansible_distribution == 'Fedora' and ansible_distribution_major_version >= '28'

- name: copy coorect version of Vagrantfile for Centos
  copy:
    src: Vagrantfile.centos
    dest: "{{ playbook_dir }}/Vagrantfile"
    owner: "{{ user }}"
    mode: 0644
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: copy coorect version of Vagrantfile for Fedora
  copy:
    src: Vagrantfile.fedora
    dest: "{{ playbook_dir }}/Vagrantfile"
    owner: "{{ user }}"
    mode: 0644
  when: ansible_distribution == 'Fedora' and ansible_distribution_major_version >= '28'

